dispatcher_base:
  url: 'http://172.18.0.22:8545'
  testing: true
  max_delay: 500
  warn_delay: 30
  services:
    -
      name: logger
      transport:
        address: 172.18.0.23
        port: 50051
  main_concern:
    abi: LoggerTestInstantiator.json
  query_port: 3001
  confirmations: 0
# contracts that needed to be deployed to blockchain
blockchain:
  number_of_accounts: 10
  networks: '7777'
  projects:
    logger:
      dependencies: []
      path: ./
      concerns:
        - Logger
      migrate_from: '1'
      migrate_to: '2'
    loggerTest:
      dependencies:
        - logger
      path: ./
      concerns:
        - LoggerTestInstantiator
      migrate_from: '3'
      migrate_to: '3'