version: '3'
services:
  ganache:
    image: trufflesuite/ganache-cli
    command: ["ganache-cli", "--accounts", "1", "--account_keys_path", "/ganache-data/keys"]
    volumes:
      - ganache_data:/ganache-data
    expose:
      - 8545
    networks:
      - ganache

  deployer:
    depends_on: [ganache]
    build:
      context: .
      dockerfile: ./deployer/Dockerfile
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    volumes:
      - truffle_data:/usr/src/app/build
    networks:
      - ganache

  key_distributor:
    depends_on: [deployer]
    image: cartesi/key-distributor
    volumes:
      - ganache_data:/keys
      - key_data:/key-0

  logger:
    depends_on: [key_distributor]
    build: .
    volumes:
      - truffle_data:/opt/cartesi/share/blockchain
      - ./test:/opt/cartesi/srv/logger-server
      - key_data:/opt/cartesi/etc/keys
    ports:
      - 50051:50051
    environment:
      WEB3_PROVIDER_URI: http://ganache:8545
    networks:
      - ganache

volumes:
  ganache_data:
  truffle_data:
  key_data:

networks:
  ganache:
