version: '3'
services:
  ganache:
    image: trufflesuite/ganache-cli
    command: ["ganache-cli", "--accounts", "1", "--account_keys_path", "/ganache-data/keys"]
    volumes:
      - ganache_data:/ganache-data
    expose:
      - 8545
    networks:
      - ganache

  deployer:
    depends_on: [ganache]
    build:
      context: .
      dockerfile: ./deployer/Dockerfile
    volumes:
      - truffle_data:/usr/src/app/build
    networks:
      - ganache

  key_distributor:
    depends_on: [deployer]
    image: cartesi/key-distributor
    volumes:
      - ganache_data:/keys
      - logger_data:/key-0

  logger_setup:
    depends_on: [key_distributor]
    build: ./setup
    volumes:
      - truffle_data:/opt/cartesi/blockchain
      - logger_data:/opt/cartesi/logger/config

  logger:
    depends_on: [logger_setup]
    build: .
    volumes:
      - truffle_data:/opt/cartesi/blockchain
      - logger_data:/opt/cartesi/logger/config
    networks:
      - ganache

volumes:
  ganache_data:
  truffle_data:
  logger_data:

networks:
  ganache:
