#!/bin/sh

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
LOGGER_DIR=${LOGGER_PATH:-${SCRIPTPATH}/test}
export PYTHONPATH=${LOGGER_DIR}/proto:${LOGGER_DIR}/..

if [[ -z "${MNEMONIC}" ]]; then
    if [[ -z "${CARTESI_CONCERN_KEY}" ]] || [[ -z "${CARTESI_CONCERN_ADDRESS}" ]]; then
        echo "Error: either MNEMONIC or both CARTESI_CONCERN_KEY and CARTESI_CONCERN_ADDRESS must be defined!"
        exit 1;
    fi
fi

cd ${LOGGER_DIR} && python3 test_logger.py $@
