#!/bin/sh

if [ $# -ne 2 ] ; then
    echo "Usage: extract-logger-address contract_json output_address_file" ;
    exit 1;
fi

CONTRACT=$(readlink -f "$1");

if [ ! -f "$CONTRACT" ]; then
    echo "$CONTRACT file not found" ;
    exit 1;
fi

jq -r '.networks | to_entries[0].value.address' $CONTRACT > $2
