name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-18.04
    services:
      hardhat:
        image: ethereumoptimism/hardhat-node
        ports:
          - 8545:8545
        options: >-
          --health-cmd "nc localhost 8545 < /dev/null"
          --health-interval 30s
          --health-timeout 10s
          --health-retries 5
          --health-start-period 30s
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: yarn install

      - uses: actions/setup-python@v1
        with:
          python-version: "3.6"
      - run: pip3 install -r requirements.txt

      - run: yarn run deploy
      - run: ./run_python_tests.sh
